- label: Google Scholar
  url: https://scholar.google.com/citations?user=JNiHto0AAAAJ
- label: ORCID
  url: https://orcid.org/0000-0002-0598-5481
- label: ResearchGate
  url: https://www.researchgate.net/profile/Tianlong-Wang-7
- label: LinkedIn
  url: https://www.linkedin.com/in/tianlong-wang/
- label: GitHub
  url: https://github.com/zjusuge
