reviewing:
- Journal of Hydrology
- Acta Geotechnica
- Bulletin of Engineering Geology and the Environment
- Stochastic Environmental Research and Risk Assessment
- Powder Technology
- PLOS ONE
- Applied Intelligence
- Earth Science Informatics
- Groundwater for Sustainable Development
- International Journal of Computational Intelligence Systems
- Journal of Rock Mechanics and Geotechnical Engineering
- Air, Soil and Water Research
- Discover Geoscience
- Earth Sciences
- Array
- International Journal of Interactive Multimedia and Artificial Intelligence
memberships:
- Chinese Society for Rock Mechanics and Engineering
- Geological Society of China
- China Civil Engineering Society
